[workspace]
resolver = "2"
members = [
  "migration",
  "crates/api", 
  "crates/utils",
  "crates/libs/server",
  "crates/libs/database",
]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
