[workspace]
resolver = "2"
members = [
  ".migration",
  "src/app", 
  "src/utils",
  "src/libs/docs",
  "src/libs/server",
  "src/libs/storage",
  "src/libs/database",
]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
